INSERT INTO Amenity (amenityID, amenityName) VALUES (1, 'WiFi');
INSERT INTO Amenity (amenityID, amenityName) VALUES (2, 'Air Conditioning');
INSERT INTO Amenity (amenityID, amenityName) VALUES (3, 'Heating');
INSERT INTO Amenity (amenityID, amenityName) VALUES (4, 'Kitchen');
INSERT INTO Amenity (amenityID, amenityName) VALUES (5, 'Washer');
INSERT INTO Amenity (amenityID, amenityName) VALUES (6, 'Dryer');
INSERT INTO Amenity (amenityID, amenityName) VALUES (7, 'Free Parking');
INSERT INTO Amenity (amenityID, amenityName) VALUES (8, 'Gym');
INSERT INTO Amenity (amenityID, amenityName) VALUES (9, 'Pool');
INSERT INTO Amenity (amenityID, amenityName) VALUES (10, 'Hot Tub');
INSERT INTO Amenity (amenityID, amenityName) VALUES (11, 'BBQ Grill');
INSERT INTO Amenity (amenityID, amenityName) VALUES (12, 'Fireplace');
INSERT INTO Amenity (amenityID, amenityName) VALUES (13, 'Breakfast');
INSERT INTO Amenity (amenityID, amenityName) VALUES (14, 'Workspace');
INSERT INTO Amenity (amenityID, amenityName) VALUES (15, 'TV');
INSERT INTO Amenity (amenityID, amenityName) VALUES (16, 'Hair Dryer');
INSERT INTO Amenity (amenityID, amenityName) VALUES (17, 'Iron');
INSERT INTO Amenity (amenityID, amenityName) VALUES (18, 'Laptop-friendly workspace');
INSERT INTO Amenity (amenityID, amenityName) VALUES (19, 'Shampoo');
INSERT INTO Amenity (amenityID, amenityName) VALUES (20, 'Essentials');
