INSERT INTO Listing (ListingID, HostID, Title, Description, Location, Price, PropertyID, MaxGuests, NumberOfGuests, Rules, CancellationPolicyID)
VALUES
    (1, 1, 'Cozy Apartment in Downtown', 'Modern and cozy apartment with city view', 'Downtown', 100.00, 1, 4, 2, 'No smoking, No pets allowed', 1),
    (2, 2, 'Luxury Villa with Private Pool', 'Spacious villa with panoramic ocean views', 'Oceanfront', 500.00, 3, 8, 4, 'Pets allowed with extra charge', 2),
    (3, 3, 'Charming Cottage in the Countryside', 'Quaint cottage surrounded by nature', 'Countryside', 80.00, 5, 2, 2, 'Quiet hours after 10 PM', 3),
    (4, 4, 'Modern Loft in the City Center', 'Stylish loft with rooftop terrace', 'City Center', 150.00, 6, 3, 2, 'No parties or events', 1),
    (5, 5, 'Secluded Cabin in the Woods', 'Remote cabin with fireplace and mountain view', 'Forest', 120.00, 4, 3, 1, 'No smoking indoors', 4),
    (6, 1, 'Beachfront Bungalow with BBQ Area', 'Cozy bungalow steps away from the beach', 'Beachfront', 200.00, 7, 4, 3, 'BBQ area available for guests', 2),
    (7, 2, 'Historic Castle with Ballroom', 'Grand castle with historic charm', 'Countryside', 1000.00, 12, 20, 10, 'Respect the historic property', 3),
    (8, 3, 'Rustic Farmhouse with Farm Experience', 'Family-friendly farmhouse with farm activities', 'Rural', 180.00, 11, 6, 4, 'Enjoy farm-fresh produce', 1),
    (9, 4, 'Modern Townhouse with City View', 'Townhouse with modern amenities and city views', 'City Center', 250.00, 17, 6, 4, 'No pets allowed', 4),
    (10, 5, 'Spacious Guesthouse with Local Tips', 'Welcoming guesthouse with local hospitality', 'Suburb', 120.00, 18, 8, 5, 'Explore nearby hiking trails', 2),
    (11, 1, 'Ski-in/Ski-out Chalet with Hot Tub', 'Chalet perfect for ski enthusiasts', 'Mountain', 300.00, 8, 6, 3, 'Hot tub available for après-ski', 1),
    (12, 2, 'Modern Penthouse with Luxury Amenities', 'Luxurious penthouse with rooftop terrace', 'Downtown', 400.00, 10, 4, 2, 'No smoking, No parties', 3),
    (13, 3, 'Peaceful Treehouse Retreat', 'Secluded treehouse getaway in nature', 'Forest', 150.00, 13, 2, 1, 'Access via ladder, Not suitable for small children', 4),
    (14, 4, 'Yacht Experience with Captain', 'Luxury yacht with onboard captain', 'Marina', 600.00, 14, 8, 6, 'Boat rules apply, No pets allowed', 1),
    (15, 5, 'Grand Mansion with Swimming Pool', 'Elegant mansion with spacious grounds', 'Suburb', 800.00, 15, 16, 10, 'Pool rules must be followed', 2),
    (16, 1, 'Urban Studio with Gym Access', 'Modern studio apartment with gym facilities', 'City Center', 80.00, 5, 2, 1, 'Quiet hours after 11 PM', 3),
    (17, 2, 'Family-Friendly Apartment with Playground', 'Apartment ideal for families with playground', 'Suburb', 120.00, 19, 6, 4, 'Children must be supervised', 4),
    (18, 3, 'Mountain View Cabin Retreat', 'Cozy cabin with stunning mountain views', 'Mountain', 100.00, 16, 3, 2, 'No smoking, No pets allowed', 1),
    (19, 4, 'Luxury Beach House with Deck', 'Beach house with oceanfront deck', 'Beachfront', 350.00, 9, 8, 6, 'Deck access restricted after 10 PM', 2),
    (20, 5, 'Farm Stay Experience with Fresh Produce', 'Farm stay with agricultural activities', 'Rural', 150.00, 20, 4, 2, 'Explore the farm, No pets allowed', 3);
