INSERT INTO Policy (policyID, policy_description) VALUES
    (1, 'Free cancellation up to 24 hours before check-in.'),
    (2, 'Full refund if canceled within 48 hours of booking.'),
    (3, 'Check-in time is after 3:00 PM.'),
    (4, 'Charged full amount for no-shows.'),
    (5, 'Pets allowed with additional cleaning fee.'),
    (6, 'Smoking is strictly prohibited.'),
    (7, 'Minimum stay of 2 nights required.'),
    (8, 'Early check-in available upon request.'),
    (9, 'Late check-out available for an additional fee.'),
    (10, 'Breakfast included in the room rate.'),
    (11, 'Complimentary Wi-Fi access.'),
    (12, 'Pool access restricted to registered guests.'),
    (13, 'Parking available at no extra charge.'),
    (14, 'Concierge service available 24/7.'),
    (15, 'Room service available from 7:00 AM to 11:00 PM.'),
    (16, 'Gym access included in the booking.'),
    (17, 'No parties or events allowed.'),
    (18, 'Additional guests subject to extra charges.'),
    (19, 'Child-friendly amenities available on request.'),
    (20, 'Deposit required upon booking, refundable per cancellation policy.');