INSERT INTO Property (PropertyID, PropertyType, Bedrooms, Bathrooms, Accommodates, Size, Amenities, ImageURL, Rating) VALUES
    (1, 'Apartment', 2, 1, 4, 80.5, 'Wi-Fi, Kitchen, Parking', 'http://example.com/apartment1.jpg', 4.5),
    (2, 'House', 3, 2, 6, 150.0, 'Garden, Pool, BBQ', 'http://example.com/house1.jpg', 4.8),
    (3, 'Villa', 4, 3, 8, 300.0, 'Private beach, Jacuzzi, Tennis court', 'http://example.com/villa1.jpg', 4.9),
    (4, 'Cabin', 1, 1, 2, 60.0, 'Fireplace, Mountain view, Pet-friendly', 'http://example.com/cabin1.jpg', 4.2),
    (5, 'Studio', 0, 1, 2, 40.0, 'Central location, Gym access', 'http://example.com/studio1.jpg', 4.0),
    (6, 'Loft', 1, 1, 3, 70.0, 'City view, Modern design', 'http://example.com/loft1.jpg', 4.7),
    (7, 'Farmhouse', 5, 3, 10, 250.0, 'Farm experience, Family-friendly', 'http://example.com/farmhouse1.jpg', 4.6),
    (8, 'Chalet', 2, 2, 4, 100.0, 'Ski-in/ski-out, Hot tub', 'http://example.com/chalet1.jpg', 4.4),
    (9, 'Beach House', 4, 2, 8, 200.0, 'Oceanfront, Deck with sea view', 'http://example.com/beachhouse1.jpg', 4.9),
    (10, 'Penthouse', 3, 3, 6, 180.0, 'Luxury amenities, Rooftop terrace', 'http://example.com/penthouse1.jpg', 4.8),
    (11, 'Bungalow', 2, 1, 4, 90.0, 'Private garden, BBQ area', 'http://example.com/bungalow1.jpg', 4.3),
    (12, 'Castle', 10, 5, 20, 1000.0, 'Historic property, Ballroom', 'http://example.com/castle1.jpg', 4.7),
    (13, 'Treehouse', 1, 0, 2, 25.0, 'Nature retreat, Secluded', 'http://example.com/treehouse1.jpg', 4.5),
    (14, 'Yacht', 3, 2, 6, 150.0, 'Boat experience, Captain included', 'http://example.com/yacht1.jpg', 4.6),
    (15, 'Mansion', 8, 6, 16, 500.0, 'Grand estate, Swimming pool', 'http://example.com/mansion1.jpg', 4.9),
    (16, 'Cottage', 2, 1, 4, 80.0, 'Quaint charm, Countryside', 'http://example.com/cottage1.jpg', 4.2),
    (17, 'Townhouse', 3, 2, 6, 120.0, 'City living, Walkable location', 'http://example.com/townhouse1.jpg', 4.1),
    (18, 'Guesthouse', 5, 3, 10, 200.0, 'Hosted experience, Local tips', 'http://example.com/guesthouse1.jpg', 4.3),
    (19, 'Apartment', 1, 1, 2, 50.0, 'Downtown, Modern amenities', 'http://example.com/apartment2.jpg', 4.0),
    (20, 'Farm Stay', 3, 2, 6, 120.0, 'Farm life, Fresh produce', 'http://example.com/farmstay1.jpg', 4.5);
