INSERT INTO Country VALUES
(1, 'Netherlands', 'NLD'),
(2, 'Germany', 'GER'),
(3, 'England', 'ENG'),
(4, 'Belgium', 'BEL'),
(5, 'Luxemburg', 'LUX'),
(6, 'France', 'FRA'),
(7, 'Spain', 'ESP'),
(8, 'Greece', 'GRK'),
(9, 'Italy', 'ITL'),
(10, 'Portugal', 'POR'),
(11, 'United States', 'USA'),
(12, 'Australia', 'AUS'),
(13, 'Denmark', 'DEN'),
(14, 'Poland', 'POL'),
(15, 'Austria', 'OST'),
(16, 'Turkey', 'TRK'),
(17, 'Norway', 'NOR'),
(18, 'Sweden', 'SWD'),
(19, 'Finland', 'FND'),
(20, 'Letland', 'LND'),
(21, 'Canada', 'CAN'),
(22, 'Mexico', 'MEX'),
(23, 'Brazil', 'BRA'),
(24, 'Argentina', 'ARG'),
(25, 'Chile', 'CHL'),
(26, 'Peru', 'PER'),
(27, 'Japan', 'JPN'),
(28, 'South Korea', 'KOR'),
(29, 'China', 'CHN'),
(30, 'India', 'IND'),
(31, 'Russia', 'RUS'),
(32, 'South Africa', 'ZAF'),
(33, 'Egypt', 'EGY'),
(34, 'Saudi Arabia', 'SAU'),
(35, 'Qatar', 'QAT'),
(36, 'New Zealand', 'NZL'),
(37, 'Thailand', 'THA'),
(38, 'Singapore', 'SGP'),
(39, 'Malaysia', 'MYS'),
(40, 'Vietnam', 'VNM'),
(41, 'Nigeria', 'NGA'),
(42, 'Kenya', 'KEN'),
(43, 'Ghana', 'GHA'),
(44, 'Ukraine', 'UKR'),
(45, 'Romania', 'ROU'),
(46, 'Hungary', 'HUN'),
(47, 'Czech Republic', 'CZE'),
(48, 'Switzerland', 'CHE'),
(49, 'Ireland', 'IRL');
