INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (1, 1, 2, 'Hello, this is a test message.', '2023-01-01');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (2, 2, 3, 'Your appointment is confirmed.', '2023-01-02');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (3, 3, 4, 'Please update your profile.', '2023-01-03');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (4, 4, 5, 'New message received.', '2023-01-04');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (5, 5, 6, 'Your order has been shipped.', '2023-01-05');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (6, 6, 7, 'Meeting scheduled for tomorrow.', '2023-01-06');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (7, 7, 8, 'Please review the document.', '2023-01-07');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (8, 8, 9, 'Your subscription has been renewed.', '2023-01-08');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (9, 9, 10, 'Password reset request.', '2023-01-09');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (10, 10, 11, 'Your account has been updated.', '2023-01-10');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (11, 11, 12, 'New friend request.', '2023-01-11');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (12, 12, 13, 'Please verify your email.', '2023-01-12');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (13, 13, 14, 'Event invitation received.', '2023-01-13');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (14, 14, 15, 'New comment on your post.', '2023-01-14');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (15, 15, 16, 'System maintenance scheduled.', '2023-01-15');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (16, 16, 17, 'Your ticket has been closed.', '2023-01-16');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (17, 17, 18, 'Congratulations on your achievement!', '2023-01-17');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (18, 18, 19, 'Your feedback is appreciated.', '2023-01-18');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (19, 19, 20, 'New update available.', '2023-01-19');
INSERT INTO Notification (NotificationID, SenderID, ReceiverID, TextMessage, NotificationDate) VALUES (20, 20, 1, 'Your request has been approved.', '2023-01-20');
