CREATE TABLE ListingAmenity(
    ListingID INTEGER,
    AmenityID INTEGER,
    CONSTRAINT FOREIGN KEY(ListingID) REFERENCES Listing ON DELETE SET NULL,
    CONSTRAINT FOREIGN KEY(AmenityID) REFERENCES Amenity ON DELETE SET NULL
    
);